# Generated by Django 5.0.6 on 2024-07-09 16:09

import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(choices=[('Maruti Suzuki', 'MARUTI SUZUKI'), ('Hyundai', 'HYUNDAI'), ('Tata Motors', 'TATA MOTORS'), ('Mahindra', 'MAHINDRA'), ('Honda', 'HONDA'), ('Skoda', 'SKODA'), ('Volkswagen', 'VOLKSWAGON'), ('Renault', 'RENAULT'), ('Toyota', 'TOYOTA'), ('Nissan', 'NISSAN'), ('MG Motor', 'MG MOTOR'), ('Kia', 'KIA'), ('Bmw', 'BMW'), ('Mercedes-Benz', 'MERCEDES-BENZ'), ('Audi', 'AUDI'), ('Jaguar', 'JAGUAR'), ('Land Rover', 'LAND ROVER'), ('Rolls Royce', 'ROLLS ROYCE'), ('Lexus', 'LEXUS'), ('Bentley', 'BENTLEY'), ('Porsche', 'PORSCHE')], default=None, max_length=26),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='engine',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='', upload_to=main.utils.user_listing_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default=None, max_length=24),
        ),
    ]
